// <auto-generated />
using System;
using Shop_Auto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Shop_Auto.Migrations
{
    [DbContext(typeof(AppDbContent))]
    partial class AppDbContentModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shop_Auto.Data.Models.Car", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<bool>("Available")
                    .HasColumnType("bit");

                b.Property<int>("CategoryId")
                    .HasColumnType("int");

                b.Property<string>("Img")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsFavourite")
                    .HasColumnType("bit");

                b.Property<string>("LongDesc")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Price")
                    .HasColumnType("int");

                b.Property<string>("ShortDesc")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("CategoryId");

                b.ToTable("Car");
            });

            modelBuilder.Entity("Shop_Auto.Data.Models.Category", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("CategoryName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Desc")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Category");
            });

            modelBuilder.Entity("Shop_Auto.Data.Models.Order", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("address")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("email")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("name")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("orderTime")
                    .HasColumnType("datetime2");

                b.Property<string>("phone")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("surname")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("id");

                b.ToTable("Order");
            });

            modelBuilder.Entity("Shop_Auto.Data.Models.OrderDetail", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int>("CarId")
                    .HasColumnType("int");

                b.Property<int>("orderId")
                    .HasColumnType("int");

                b.Property<long>("price")
                    .HasColumnType("bigint");

                b.HasKey("id");

                b.HasIndex("CarId");

                b.HasIndex("orderId");

                b.ToTable("OrderDetail");
            });

            modelBuilder.Entity("Shop_Auto.Data.Models.ShopCartItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("ShopCartId")
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("carId")
                    .HasColumnType("int");

                b.Property<int>("price")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("carId");

                b.ToTable("ShopCartItem");
            });

            modelBuilder.Entity("Shop_Auto.Data.Models.Car", b =>
            {
                b.HasOne("Shop_Auto.Data.Models.Category", "Category")
                    .WithMany("Cars")
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Category");
            });

            modelBuilder.Entity("Shop_Auto.Data.Models.OrderDetail", b =>
            {
                b.HasOne("Shop_Auto.Data.Models.Car", "car")
                    .WithMany()
                    .HasForeignKey("CarId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Shop_Auto.Data.Models.Order", "order")
                    .WithMany("orderDetails")
                    .HasForeignKey("orderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("car");

                b.Navigation("order");
            });

            modelBuilder.Entity("Shop_Auto.Data.Models.ShopCartItem", b =>
            {
                b.HasOne("Shop_Auto.Data.Models.Car", "car")
                    .WithMany()
                    .HasForeignKey("carId");

                b.Navigation("car");
            });

            modelBuilder.Entity("Shop_Auto.Data.Models.Category", b =>
            {
                b.Navigation("Cars");
            });

            modelBuilder.Entity("Shop_Auto.Data.Models.Order", b =>
            {
                b.Navigation("orderDetails");
            });
#pragma warning restore 612, 618
        }
    }
}
